puts "🔄 Réinitialisation des données…"
# On vide les tables pour éviter les doublons

Question.destroy_all
ContentTag.destroy_all
Note.destroy_all
Content.destroy_all
User.destroy_all


puts "✅ Tables vidées"
puts "🔄 Création des users en cours…"


matis = User.create!(
  id:       6,
  email:    "matis@example.com",
  password: "password",
  nickname: "matis"
)

augustin = User.create!(
  id:       7,
  email:    "augustin@example.com",
  password: "password",
  nickname: "augustin"
)

vincent = User.create!(
  id:       8,
  email:    "vincent@example.com",
  password: "password",
  nickname: "Vincent"
)

jean = User.create!(
  id:       9,
  email:    "jean@example.com",
  password: "password",
  nickname: "jean"
)

puts "✅ #{User.count} users créés : #{User.pluck(:nickname).join(', ')}"

puts "🔄 Création des content en cours…"
content = Content.create!(
id: 25,
 source_type: "youtube_video",
 url: "https://www.youtube.com/watch?v=FbjL5OMOB58",
 thumbnail: "https://i.ytimg.com/vi/FbjL5OMOB58/maxresdefault.jpg",
 name: "À quoi ressemblait l'Arabie avant l'arrivée de l'Islam ?",
 duration: 759,
 language: "fr",
 summary:
  "Le texte aborde plusieurs sujets liés à l'histoire de l'Arabie avant et après l'Islam. \n\nPremièrement, il traite de la confusion fréquente entre \"arabe\" et \"musulman\", expliquant que l'Arabie est devenue centrale dans l'histoire mondiale en tant que berceau de l'Islam au 7e siècle, bien que son importance commerciale préexistait déjà. L'Arabie, bien avant l'Islam, servait de plateforme commerciale mondiale, abritant plusieurs royaumes prospères.\n\nEnsuite, le texte décrit la géographie de l'Arabie, caractérisée par ses déserts et ses montagnes, et son influence sur la formation des royaumes dans des vallées fertiles. L'évolution du climat y est également décrite, montrant comment les variations climatiques ont influencé la vie et les migrations humaines au fil des millénaires. \n\nLe développement de la sédentarisation dans les montagnes du Yémen vers 2000 avant notre ère est aussi abordé, avec l'apparition de cités organisées et de structures sociales complexes. Les échanges commerciaux avec la Mésopotamie et la civilisation de l'Indus sont mentionnés, illustrant une société arabe intégrée dans un réseau commercial international.\n\nLa domestication du dromadaire à la fin du 2e millénaire avant notre ère est un autre point clé, transformant le désert en un passage commercial crucial entre l'Europe et l'Inde, facilitant ainsi l'apparition de nouveaux royaumes marchands.\n\nLe texte explore ensuite l'arrivée des Romains qui, bien que ne parvenant pas à conquérir l'Arabie, influencent son commerce en redirigeant les routes marchandes au profit de l'Empire romain, ce qui affaiblit les royaumes arabes traditionnels. \n\nEnfin, le texte relate l'évolution politique et religieuse de l'Arabie, avec l'influence croissante des puissances byzantine et éthiopienne, jusqu'à l'émergence de l'Islam sous Mohammed, qui marque le début d'une nouvelle ère de conquêtes et d'expansion pour les Arabes.",
 user_id: jean.id,
 transcription:[
  {"text"=>"Mes chers camarades, bien le bonjour ! Est-ce \nque ça vous arrive encore de croiser des gens qui  ",
  "duration"=>3960,
  "offset"=>120,
  "lang"=>"fr"},
 {"text"=>
   "confondent “arabe” et “musulman” ? Alors, c’est surtout \nparce que l’Arabie, elle est entrée dans l’Histoire  ",
  "duration"=>5100,
  "offset"=>4080,
  "lang"=>"fr"},
 {"text"=>
   "mondiale au moment où elle est devenue le berceau \nde l’Islam au 7e siècle. C’est là que le prophète  ",
  "duration"=>5280,
  "offset"=>9180,
  "lang"=>"fr"},
 {"text"=>
   "Mohammed a vécu, a fixé des lieux saints, \net est parti à la conquête du monde. De fait,  ",
  "duration"=>4620,
  "offset"=>14460,
  "lang"=>"fr"},
 {"text"=>
   "l’Arabie reste au centre de l’espace musulman, \nqui va de l’Espagne jusqu’à l’Indonésie !",
  "duration"=>4376,
  "offset"=>19080,
  "lang"=>"fr"},
 {"text"=>
   "Mais l’Arabie existait bien avant l’Islam ! Alors, \nokay, c’est pas l’Égypte ou la Mésopotamie,  ",
  "duration"=>5464,
  "offset"=>23456,
  "lang"=>"fr"},
 {"text"=>
   "mais à la marge de ces empires, l’Arabie \nformait une plateforme du commerce mondial,  ",
  "duration"=>4019.9999999999995,
  "offset"=>28920,
  "lang"=>"fr"},
 {"text"=>
   "où plusieurs royaumes sont devenus très prospères… \nEt c’est eux qu’on va découvrir aujourd’hui !",
  "duration"=>6046,
  "offset"=>32940,
  "lang"=>"fr"},
 {"text"=>"*Musique*", "duration"=>8633, "offset"=>38986, "lang"=>"fr"},
 {"text"=>
   "L’Arabie, c’est 3 millions de kilomètres carrés, dont une \ngrande majorité de désert. On parle de péninsule  ",
  "duration"=>6861,
  "offset"=>47619,
  "lang"=>"fr"},
 {"text"=>
   "arabique, parce qu’elle est entourée par l’eau : \nla mer Rouge à l’o
uest, l’océan Indien au  ",
  "duration"=>5040,
  "offset"=>54480,
  "lang"=>"fr"},
 {"text"=>
   "sud, et le golfe persique à l’est. Mais côté \nnord, elle est reliée
directement à l’Asie,  ",
  "duration"=>5640,
  "offset"=>59520,
  "lang"=>"fr"},
 {"text"=>
   "à l’Afrique, et au Proche-Orient, tout près de \nl’Europe. En plus du
 désert, manque de bol,  ",
  "duration"=>4920,
  "offset"=>65160,
  "lang"=>"fr"},
 {"text"=>
   "l’Arabie est encadrée par deux chaînes de montagne : \nune petite à l
’Est, une immense à l’Ouest,  ",
  "duration"=>5880,
  "offset"=>70080,
  "lang"=>"fr"},
 {"text"=>
   "et les deux culminent à 3.000 et 3.600 mètres. \nLargement assez pour
 bloquer la plupart des  ",
  "duration"=>5880,
  "offset"=>75960,
  "lang"=>"fr"},
 {"text"=>
   "pluies de l’océan Indien, ce qui explique le désert \ndu centre ! Dit
es vous qu'il pleut tellement peu que  ",
  "duration"=>4740,
  "offset"=>81840,
  "lang"=>"fr"},
 {"text"=>
   "c’est une des rares régions du monde qui n’abrite \npas de lac ni de
rivière permanente. Au centre,  ",
  "duration"=>4920,
  "offset"=>86580,
  "lang"=>"fr"},
 {"text"=>
   "tout simplement, il n’y a pas grand chose. Mais \nses montagnes ont u
n avantage : les deux  ",
  "duration"=>5040,
  "offset"=>91500,
  "lang"=>"fr"},
 {"text"=>
   "chaînes abritent en réalité des \nvallées et des oasis tempérées.",
  "duration"=>3480,
  "offset"=>96540,
  "lang"=>"fr"},
 {"text"=>
   "Pendant des millénaires, c’est dans ces planques \nsecrètes et fertil
es que vont naître tous les  ",
  "duration"=>4860,
  "offset"=>100020,
  "lang"=>"fr"},
 {"text"=>
   "grands royaumes d’Arabie. Il faut dire qu’en \ndehors, le climat vari
e beaucoup avec le temps.",
  "duration"=>3660,
  "offset"=>104880,
  "lang"=>"fr"},
 {"text"=>
   "Pendant la dernière glaciation, il y a 20.000 ans, \nle climat était
encore plus aride. Seul le Golfe  ",
  "duration"=>6120,
  "offset"=>108540,
  "lang"=>"fr"},
 {"text"=>
   "persique, alimenté par Tigre et de l’Euphrate, devait \nêtre accueill
ant. Vers 8000 à 4000 avant notre ère,  ",
  "duration"=>6580,
  "offset"=>114660,
  "lang"=>"fr"},
 {"text"=>
   "les pluies de l’Océan Indien sont plus nombreuses \net atteignent le
centre des terres. Des lacs et  ",
  "duration"=>4640,
  "offset"=>121240,
  "lang"=>"fr"},
 {"text"=>
   "des rivières apparaissent, et font naître une \nbelle savane. Les cha
sseurs-cueilleurs sont ravis,  ",
  "duration"=>4019.9999999999995,
  "offset"=>125880,
  "lang"=>"fr"},
 {"text"=>
   "d’autant que la mer leur fournit \nen plus toutes sortes de poissons
!",
  "duration"=>2997,
  "offset"=>129900,
  "lang"=>"fr"},
 {"text"=>
   "Il faut se dire qu’à cette époque, même \nle Sahara était verdoyant,
et d’ailleurs,  ",
  "duration"=>3483,
  "offset"=>132897,
  "lang"=>"fr"},
 {"text"=>
   "on a fait un épisode là-dessus, \nvous avez le lien en description !",
  "duration"=>3450,
  "offset"=>136380,
  "lang"=>"fr"},
 {"text"=>
   "Du coup l’Arabie est plutôt bien peuplée : on \ndécouvre par exemple
des peintures rupestres  ",
  "duration"=>4650,
  "offset"=>139830,
  "lang"=>"fr"},
 {"text"=>
   "aux alentours de Najran. Mais aussi des traces \nde bétail domestiqué
 : les populations d’Arabie  ",
  "duration"=>4740,
  "offset"=>144480,
  "lang"=>"fr"},
 {"text"=>
   "sont des pasteurs nomades, qui suivent \nleurs troupeaux de moutons e
t de chèvres.  ",
  "duration"=>3780,
  "offset"=>149220,
  "lang"=>"fr"},
 {"text"=>
   "Ils maîtrisent néanmoins l’agriculture, avec \npar exemple la culture
 du palmier dattier,  ",
  "duration"=>4680,
  "offset"=>153000,
  "lang"=>"fr"},
 {"text"=>
   "qui date du 5e millénaire avant notre ère. Enfin, \nles habitants d’A
rabie ont laissé derrière eux  ",
  "duration"=>5160,
  "offset"=>157680,
  "lang"=>"fr"},
 {"text"=>
   "d’autres vestiges archéologiques : des cairns \nfunéraires bâtis en h
auteur pour inhumer un  ",
  "duration"=>4600,
  "offset"=>162840,
  "lang"=>"fr"},
 {"text"=>
   "individu, et sans doute pour marquer le territoire \nde son clan. Les
 archéologues ont aussi fait une  ",
  "duration"=>5480,
  "offset"=>167440,
  "lang"=>"fr"},
 {"text"=>
   "découverte un peu plus étrange, les mustatils :\ndes rectangles de pi
erre situés en plein  ",
  "duration"=>4980,
  "offset"=>172920,
  "lang"=>"fr"},
 {"text"=>
   "désert du Nefud, qui avaient peut-être une fonction \nreligieuse. Eux
 aussi, datent d’environ 5.000 avant notre ère.",
  "duration"=>5460,
  "offset"=>177900,
  "lang"=>"fr"},
 {"text"=>
   "Et voilà, l’aridité revient enfin en 4.000 avant notre ère, \nles gen
s quittent le centre du pays, et on commence à  ",
  "duration"=>6360,
  "offset"=>183360,
  "lang"=>"fr"},
 {"text"=>
   "avoir un climat un petit peu comme aujourd’hui. Alors \nlà, vous vous
 dites que la péninsule va se vider  ",
  "duration"=>4500,
  "offset"=>189720,
  "lang"=>"fr"},
 {"text"=>
   "complètement… sauf que non ! Il y a la mer, et puis il \ny a les fame
uses montagnes qui gardent l’humidité. Et  ",
  "duration"=>6180,
  "offset"=>194220,
  "lang"=>"fr"},
 {"text"=>
   "comme l’Âge du Bronze connaît un renouveau, \nla population d’Arabie
va même augmenter !",
  "duration"=>4560,
  "offset"=>200400,
  "lang"=>"fr"},
 {"text"=>
   "D’ailleurs, on se sédentarise, dans les \nmontagnes du Yémen ! Vers 2
.000 avant notre ère,  ",
  "duration"=>4800,
  "offset"=>204960,
  "lang"=>"fr"},
 {"text"=>
   "de véritables citées apparaissent, avec leurs \nchamps bien irrigués
par des canaux. Sabir,  ",
  "duration"=>4980,
  "offset"=>209760,
  "lang"=>"fr"},
 {"text"=>
   "par exemple, avait des remparts de brique, de \nnombreux ateliers de
potiers et de métallurgistes,  ",
  "duration"=>5040,
  "offset"=>214740,
  "lang"=>"fr"},
 {"text"=>
   "ainsi qu’un vaste sanctuaire comparable à ceux \nde Mésopotamie. Dans
 la région de Magan,  ",
  "duration"=>5460,
  "offset"=>219780,
  "lang"=>"fr"},
 {"text"=>
   "on retrouve des sépultures circulaires. À \nl’oasis d’Al Aïn, elles p
euvent faire jusqu’à  ",
  "duration"=>4620,
  "offset"=>225240,
  "lang"=>"fr"},
 {"text"=>
   "14 m de diamètre et accueillir 700 individus d’un \nclan ou d’une mêm
e famille. Et là, on ne parle pas  ",
  "duration"=>5580,
  "offset"=>229860,
  "lang"=>"fr"},
 {"text"=>
   "d’un vulgaire tas de terre : parées de pierres \najustées et sculptée
s, ces tombes contiennent de  ",
  "duration"=>4800,
  "offset"=>235440,
  "lang"=>"fr"},
 {"text"=>
   "riches objets en lapis-lazuli, en cornaline, en or \net en argent. C’
est la preuve d’un lien commercial  ",
  "duration"=>5820,
  "offset"=>240240,
  "lang"=>"fr"},
 {"text"=>
   "avec la Mésopotamie et la civilisation de l’Indus, \ndans l’actuel Pa
kistan. En échange, Magan fournit  ",
  "duration"=>6300,
  "offset"=>246060,
  "lang"=>"fr"},
 {"text"=>
   "du cuivre, transporté dans de grands navires \nétanchéifiés au bitume
, un dérivé du pétrole de  ",
  "duration"=>4920,
  "offset"=>252360,
  "lang"=>"fr"},
 {"text"=>
   "la région. Sur l’île de Bahreïn, la civilisation de \nDilmoun fait en
core mieux : on a recensé 75.000  ",
  "duration"=>7380,
  "offset"=>257279.99999999997,
  "lang"=>"fr"},
 {"text"=>
   "tumulus allant jusqu’à 30 mètres de diamètre. \nAux environs d’Aali p
ar exemple, le paysage  ",
  "duration"=>5820,
  "offset"=>264660,
  "lang"=>"fr"},
 {"text"=>
   "n’est qu’un champ de bosses : ce sont des tombes \nà perte de vue, to
utes construites en à peine cinq  ",
  "duration"=>5940,
  "offset"=>270480,
  "lang"=>"fr"},
 {"text"=>
   "siècles. En effet, l’île, au centre du commerce \nde perles, connaît
un pic de civilisation. La  ",
  "duration"=>5760,
  "offset"=>276420,
  "lang"=>"fr"},
 {"text"=>
   "grande cité de Qala’at al-Bahraïn, avec ses \nvastes bâtiments et sa
muraille de pierre,  ",
  "duration"=>4320,
  "offset"=>282180,
  "lang"=>"fr"},
 {"text"=>
   "prouve la puissance de Dilmoun, souvent citée \ndans les tablettes cu
néiformes de Mésopotamie.",
  "duration"=>5340,
  "offset"=>286500,
  "lang"=>"fr"},
 {"text"=>
   "Bref : à l’Âge du Bronze, on rigole pas \nvraiment en Arabie ! Toutes
 les côtes sont  ",
  "duration"=>4140,
  "offset"=>293040,
  "lang"=>"fr"},
 {"text"=>
   "habitées et prospèrent. Il n’y a \nque le désert central qui est à  ",
  "duration"=>3540,
  "offset"=>297180,
  "lang"=>"fr"},
 {"text"=>
   "l’abandon… Mais ça aussi ça va changer, \ngrâce à la révolution du dr
omadaire !",
  "duration"=>3840,
  "offset"=>300720,
  "lang"=>"fr"},
 {"text"=>"*Musique*", "duration"=>4440, "offset"=>304560, "lang"=>"fr"},
 {"text"=>
   "La domestication du dromadaire à la fin du 2e millénaire \navant notr
e ère va absolument tout changer ! Capable  ",
  "duration"=>6360,
  "offset"=>309000,
  "lang"=>"fr"},
 {"text"=>
   "de passer trois semaines sans boire en pleine \nsaison chaude, il se
déplace loin et rapidement.  ",
  "duration"=>4860,
  "offset"=>315360,
  "lang"=>"fr"},
 {"text"=>
   "Les nomades bédouins reprennent alors l’avantage : \nils peuvent loue
r leurs animaux, mais aussi servir  ",
  "duration"=>5160,
  "offset"=>320220,
  "lang"=>"fr"},
 {"text"=>
   "d’escorte et de guide aux marchands. Le long et \ndangereux détour pa
r la mer Rouge n’est alors plus  ",
  "duration"=>4800,
  "offset"=>325380,
  "lang"=>"fr"},
 {"text"=>
   "nécessaire ! Désormais, le désert devient le point \nde passage entre
 l’Europe et l’Océan Indien ! Et  ",
  "duration"=>6120,
  "offset"=>330180,
  "lang"=>"fr"},
 {"text"=>
   "ça, ça va durer toute l’Antiquité ! Chaque oasis \noffre eau, vivres
et abri, moyennant une petite taxe  ",
  "duration"=>7380,
  "offset"=>336300,
  "lang"=>"fr"},
 {"text"=>
   "sur les produits de luxe qui sont transportés, \nen particulier la my
rrhe et l’encens, deux  ",
  "duration"=>4500,
  "offset"=>343680,
  "lang"=>"fr"},
 {"text"=>
   "résines qui sont précieuses, puisque la myrrhe permet de \nfabriquer
des parfums et des onguents. L’encens quant à lui,",
  "duration"=>6000,
  "offset"=>348180,
  "lang"=>"fr"},
 {"text"=>
   "dégage une bonne odeur en brûlant, et participe \nà tous les rituels
religieux grecs et romains.",
  "duration"=>4860,
  "offset"=>354180,
  "lang"=>"fr"},
 {"text"=>
   "Donc tout le monde s’arrache ces \nproduits à des prix exorbitants,
",
  "duration"=>3840,
  "offset"=>359040,
  "lang"=>"fr"},
 {"text"=>
   "au point que des nouveaux royaumes \nmarchands vont apparaitre. Et ce
 sont eux  ",
  "duration"=>3720,
  "offset"=>362880,
  "lang"=>"fr"},
 {"text"=>
   "les premiers qui vont être nommés « Arabes » dans \nun texte assyrien
 qui est daté de 853 avant notre ère.",
  "duration"=>6120,
  "offset"=>366600,
  "lang"=>"fr"},
 {"text"=>
   "Les Arabes ne font donc pas partie des \ngrands empires alentours. Il
s préfèrent  ",
  "duration"=>3720,
  "offset"=>372720,
  "lang"=>"fr"},
 {"text"=>
   "fonder une multitude de petits royaumes, \nsouvent autour d’un oasis
comme Al-Ula,  ",
  "duration"=>4200,
  "offset"=>376440,
  "lang"=>"fr"},
 {"text"=>
   "capitale du royaume de Dadan. C’est aussi le cas \nde chaque vallée d
u Yémen, comme Hadramaout,  ",
  "duration"=>5340,
  "offset"=>380640,
  "lang"=>"fr"},
 {"text"=>
   "Awsan, Qataban et Saba : à chacun son sanctuaire \net son dieu protec
teur, le tout formant un vaste  ",
  "duration"=>6060,
  "offset"=>385980,
  "lang"=>"fr"},
 {"text"=>
   "panthéon polythéiste. On ne sait presque rien \nde cette religion, sa
uf qu’ils étaient attachés à la  ",
  "duration"=>4680,
  "offset"=>392040,
  "lang"=>"fr"},
 {"text"=>
   "pureté et à la main droite, deux éléments qui ont \nd’ailleurs perdur
é dans l’Islam ! Mais tout change  ",
  "duration"=>4980,
  "offset"=>396720,
  "lang"=>"fr"},
 {"text"=>
   "au 7e siècle avant notre ère, lorsque le roi de \nSaba, Karib’il Wata
r, unifie la majeure partie du  ",
  "duration"=>5460,
  "offset"=>401700,
  "lang"=>"fr"},
 {"text"=>
   "Yémen. Sa capitale, Ma’rib, est réputée pour ses \nimmenses ouvrages
hydrauliques qui ont permis de  ",
  "duration"=>5220,
  "offset"=>407160,
  "lang"=>"fr"},
 {"text"=>
   "cultiver des milliers d’hectares, et ont assuré \nla prospérité du ro
yaume pendant 1500 ans. Une  ",
  "duration"=>5160,
  "offset"=>412380,
  "lang"=>"fr"},
 {"text"=>
   "grande digue, haute de 15m et longue de 650 \nmètres, retenait l’eau
du fleuve Dhana. Elle  ",
  "duration"=>6060,
  "offset"=>417540,
  "lang"=>"fr"},
 {"text"=>
   "incluait un système d’écluses, qui alimentait \ndes canaux d’irrigati
on de tout l’oasis.",
  "duration"=>4590,
  "offset"=>423600,
  "lang"=>"fr"},
 {"text"=>
   "À cette époque, les Grecs commencent à faire \nla liste des 7 merveil
les du monde : et c’est sûr,  ",
  "duration"=>4950,
  "offset"=>428190,
  "lang"=>"fr"},
 {"text"=>"s’ils avaient connu cette \ndigue, elle en ferait partie !",
  "duration"=>3540,
  "offset"=>433140,
  "lang"=>"fr"},
 {"text"=>
   "On peut aussi parler d’un autre royaume, \nMa’in. Apparu au 6e siècle
 avant notre ère,  ",
  "duration"=>5040,
  "offset"=>436680,
  "lang"=>"fr"},
 {"text"=>
   "il est à la fois nomade et sédentaire, et se \nspécialise dans le com
merce. Ses marchands  ",
  "duration"=>5700,
  "offset"=>441720,
  "lang"=>"fr"},
 {"text"=>
   "étendent leurs réseaux jusqu’en Égypte \net en Mésopotamie. Les Minée
ns sont si  ",
  "duration"=>4440,
  "offset"=>447420,
  "lang"=>"fr"},
 {"text"=>
   "puissants qu’ils dominent l’oasis d’Al-Ula \npendant des siècles. Et
leur alphabet,  ",
  "duration"=>4200,
  "offset"=>451860,
  "lang"=>"fr"},
 {"text"=>
   "qui se rapproche de l’araméen, va se transformer \njusqu’à constituer
 l’alphabet arabe.",
  "duration"=>4260,
  "offset"=>456060,
  "lang"=>"fr"},
 {"text"=>"Et je finis cette liste des \nroyaumes par un autre  ",
  "duration"=>3180,
  "offset"=>460320,
  "lang"=>"fr"},
 {"text"=>
   "état très puissant, situé au Nord de \nla péninsule : celui des Nabat
éens.",
  "duration"=>4680,
  "offset"=>463500,
  "lang"=>"fr"},
 {"text"=>
   "Leur capitale, Pétra, est coincée entre \nl’Inde, les grands royaumes
 grecs,  ",
  "duration"=>4680,
  "offset"=>468180,
  "lang"=>"fr"},
 {"text"=>
   "les Égyptiens lagides, et les Perses séleucides. \nPourtant, ils vont
 survivre, tout simplement parce  ",
  "duration"=>6180,
  "offset"=>472860,
  "lang"=>"fr"},
 {"text"=>
   "qu’ils assurent le commerce entre tous ces mondes \ntrès différents.
Pétra est d’ailleurs célèbre pour  ",
  "duration"=>4320,
  "offset"=>479040,
  "lang"=>"fr"},
 {"text"=>
   "son architecture troglodyte, qui s’est ensuite \nrépandue jusqu’à Al-
Ula. Leurs riches tombeaux  ",
  "duration"=>5040,
  "offset"=>483360,
  "lang"=>"fr"},
 {"text"=>
   "creusés dans les falaises de grès et les milliers \nd’inscriptions no
us renseignent sur leur noblesse,  ",
  "duration"=>4680,
  "offset"=>488400,
  "lang"=>"fr"},
 {"text"=>
   "leurs dieux et leurs cultes. Certaines de leurs \ntraditions ont même
 peut-être influencés  ",
  "duration"=>4320,
  "offset"=>493080,
  "lang"=>"fr"},
 {"text"=>
   "l’Islam médiéval. Par exemple, ils représentaient \nleur dieu Dhū-Sha
rà par une pierre quadrangulaire  ",
  "duration"=>5580,
  "offset"=>497400,
  "lang"=>"fr"},
 {"text"=>
   "noire, qui fait beaucoup penser à la Kaaba \nde la Mecque. Un autre d
e leur dieu exigeait  ",
  "duration"=>4860,
  "offset"=>502980,
  "lang"=>"fr"},
 {"text"=>
   "de ne pas boire de vin, tout comme le \nCoran plus tard préconisera d
’éviter ça !",
  "duration"=>4230,
  "offset"=>507840,
  "lang"=>"fr"},
 {"text"=>
   "Mais on est encore loin du Moyen Âge ! Et ce qui \nva radicalement ch
anger la politique en Arabie,  ",
  "duration"=>5130,
  "offset"=>512070.00000000006,
  "lang"=>"fr"},
 {"text"=>
   "c’est l’arrivée d’une puissance \ntrès ambitieuse : l’Empire romain !
",
  "duration"=>4230,
  "offset"=>517200.00000000006,
  "lang"=>"fr"},
 {"text"=>
   "Depuis le Ier siècle avant notre ère, \nles Romains sont assez proche
s de  ",
  "duration"=>3330,
  "offset"=>521429.99999999994,
  "lang"=>"fr"},
 {"text"=>
   "la péninsule arabique : normal, puisqu’ils \ns'intéressent à l’encens
 et à la myrrhe. Mais  ",
  "duration"=>4620,
  "offset"=>524760,
  "lang"=>"fr"},
 {"text"=>
   "ils s’incrustent de plus en plus dans les affaires \nde la région, au
 point qu’en 26 avant notre ère,  ",
  "duration"=>4620,
  "offset"=>529380,
  "lang"=>"fr"},
 {"text"=>
   "l’empereur Auguste envoie deux légions pour \nconquérir la célèbre “A
rabie heureuse”. Mais  ",
  "duration"=>4800,
  "offset"=>534000,
  "lang"=>"fr"},
 {"text"=>
   "même sans rencontrer de grosse résistance, \nl’armée renonce après se
ulement une semaine  ",
  "duration"=>4200,
  "offset"=>538800,
  "lang"=>"fr"},
 {"text"=>
   "de siège devant Ma’rib. La faim, la soif et \nla maladie forcent le p
réfet Aelius Gallus à  ",
  "duration"=>7440,
  "offset"=>543000,
  "lang"=>"fr"},
 {"text"=>
   "faire demi-tour : il a été vaincu par le \ndésert, qui est la meilleu
re des défenses !",
  "duration"=>4740,
  "offset"=>550440,
  "lang"=>"fr"},
 {"text"=>
   "Alors ok, mais même sans posséder l’Arabie, \nest-ce  qu’il y aurait
pas moyen de contrôler son  ",
  "duration"=>4620,
  "offset"=>555180,
  "lang"=>"fr"},
 {"text"=>
   "commerce ? Il y a tellement d’étapes entre Ma’in et Pétra : \n70 jour
s de marche quand même ! Et à chaque fois,  ",
  "duration"=>5760,
  "offset"=>559800,
  "lang"=>"fr"},
 {"text"=>
   "c'est des taxes, des frais, etc. Ce qui fait qu’une fois arrivée \nen
 Méditerranée, le prix de la marchandise, il est exorbitant !",
  "duration"=>6040,
  "offset"=>565560,
  "lang"=>"fr"},
 {"text"=>
   "Les Romains prennent alors le port \nd’Aila, aujourd’hui Eilat, en Is
raël : de là,  ",
  "duration"=>4380,
  "offset"=>571620,
  "lang"=>"fr"},
 {"text"=>
   "ils ont une liaison maritime directe. \nQuitte à prendre le risque de
 la mer,  ",
  "duration"=>3180,
  "offset"=>576000,
  "lang"=>"fr"},
 {"text"=>
   "Rome rebat complètement les cartes : elle \nn’achètera plus rien aux
Bédouins ! Ils  ",
  "duration"=>4260,
  "offset"=>579180,
  "lang"=>"fr"},
 {"text"=>
   "commercent uniquement avec le royaume \nd’Himyar et sa capitale de Za
far,  ",
  "duration"=>3480,
  "offset"=>583440,
  "lang"=>"fr"},
 {"text"=>
   "qui devient soudain le principal nœud commercial de \nla région. Les
autres royaumes arabes perdent alors",
  "duration"=>5040,
  "offset"=>586920,
  "lang"=>"fr"},
 {"text"=>
   "une part importante de leurs revenus. L’empereur \nTrajan installe mê
me une garnison romaine sur les  ",
  "duration"=>4800,
  "offset"=>591960,
  "lang"=>"fr"},
 {"text"=>
   "îles Farasan pour sécuriser le commerce de la Mer \nRouge. Situé à 4.
000 kilomètres de Rome, c’est le  ",
  "duration"=>6060,
  "offset"=>596760,
  "lang"=>"fr"},
 {"text"=>
   "plus lointain avant-poste de tout l’Empire. Et \nen 106, lorsque le r
oi des Nabatéens Rabbel II  ",
  "duration"=>5880,
  "offset"=>602820,
  "lang"=>"fr"},
 {"text"=>
   "meurt sans héritier, son royaume est annexé pour \ndevenir la provinc
e d’Arabie. Une autre légion  ",
  "duration"=>4980,
  "offset"=>608700,
  "lang"=>"fr"},
 {"text"=>
   "y est transférée, et à présent, Rome occupe tout \nle nord-ouest de l
’Arabie, jusqu’à l’oasis d’Al-Ula.",
  "duration"=>5940,
  "offset"=>613680,
  "lang"=>"fr"},
 {"text"=>
   "Des remparts romains ont d’ailleurs été récemment \ndécouverts dans c
ette région ! Et ils servaient pas  ",
  "duration"=>4380,
  "offset"=>619620,
  "lang"=>"fr"},
 {"text"=>
   "à rien, parce que pour rappel : au 3e siècle, Rome, \ndésolé, ne domi
nait pas toute la région, loin de là !",
  "duration"=>6390,
  "offset"=>624000,
  "lang"=>"fr"},
 {"text"=>
   "Au nord-ouest, les Ghassanides, une \ntribu convertie au christianism
e,  ",
  "duration"=>3210,
  "offset"=>630390,
  "lang"=>"fr"},
 {"text"=>
   "protègent bien l’empire Romain, puis \nByzantin, quand Rome tombe. À
l'est,  ",
  "duration"=>4920,
  "offset"=>633600,
  "lang"=>"fr"},
 {"text"=>
   "les Arabes Lakhmides contrôlent le Golfe persique \npour le compte de
 l’Empire Perse sassanide.  ",
  "duration"=>4680,
  "offset"=>638520,
  "lang"=>"fr"},
 {"text"=>
   "Au sud, le royaume d’Himyar gagne en puissance, \ns’empare d’une gran
de partie du désert intérieur,  ",
  "duration"=>5820,
  "offset"=>643200,
  "lang"=>"fr"},
 {"text"=>
   "de la mer Rouge, et même de quelques dépendances \nsur la rive africa
ine. Vers 380, les souverains  ",
  "duration"=>6480,
  "offset"=>649020,
  "lang"=>"fr"},
 {"text"=>
   "himyarites se convertissent au Judaïsme, une \nfaçon de reconnaître l
es nombreuses communautés  ",
  "duration"=>4560,
  "offset"=>655500,
  "lang"=>"fr"},
 {"text"=>
   "juives du pays, mais aussi d’affirmer leur \nindépendance face aux pu
issants voisins chrétiens  ",
  "duration"=>4380,
  "offset"=>660060,
  "lang"=>"fr"},
 {"text"=>
   "de Byzance et d’Éthiopie. Ce qui se comprend, \nparce que l’Éthiopie
tente d’influencer le royaume,  ",
  "duration"=>4860,
  "offset"=>664440,
  "lang"=>"fr"},
 {"text"=>
   "voire finance des coups d’état ! Face à tout ça, en \n522 le roi Yusu
f, ou Dhu Nuwas, s’impose. Juif  ",
  "duration"=>8100,
  "offset"=>669300,
  "lang"=>"fr"},
 {"text"=>
   "radical, il persécute et massacre les chrétiens du \nroyaume. Le Négu
s Caleb, à la tête des Éthiopiens,  ",
  "duration"=>5640,
  "offset"=>677400,
  "lang"=>"fr"},
 {"text"=>
   "réagit en envahissant le pays avec l’aide \nde la flotte byzantine, e
t Yusuf est vaincu.",
  "duration"=>4680,
  "offset"=>683040,
  "lang"=>"fr"},
 {"text"=>"L’Éthiopie met en place un \nprotectorat : donc pendant  ",
  "duration"=>3840,
  "offset"=>687720,
  "lang"=>"fr"},
 {"text"=>"un moment, le pays est en \nfait dirigé par des Chrétiens !",
  "duration"=>3240,
  "offset"=>691560,
  "lang"=>"fr"},
 {"text"=>
   "D’ailleurs, leurs aristocrates font construire \nla cathédrale de San
aa. Depuis, elle a servi  ",
  "duration"=>5160,
  "offset"=>694800,
  "lang"=>"fr"},
 {"text"=>
   "de carrière pour construire la grande mosquée de \nla ville. Et c’est
 pour ça qu’on y retrouve encore  ",
  "duration"=>4080,
  "offset"=>699960,
  "lang"=>"fr"},
 {"text"=>
   "deux chapiteaux de colonne qui portent des croix ! \nMais ça ne dure
pas longtemps : après quelques  ",
  "duration"=>4980,
  "offset"=>704040,
  "lang"=>"fr"},
 {"text"=>
   "décennies, le prince juif Sayf ibn dhî-Yaz’an \nchasse les Chrétiens.
 Mais pour ça,  ",
  "duration"=>5280,
  "offset"=>709020,
  "lang"=>"fr"},
 {"text"=>
   "il a reçu le soutien des Perses, qui à leur \ntour contrôlent l’Arabi
e dans les années 570.",
  "duration"=>5160,
  "offset"=>714300,
  "lang"=>"fr"},
 {"text"=>
   "Mais le pays connaît une dernière bascule ! \nDans les années 620, de
 nombreuses  ",
  "duration"=>4440,
  "offset"=>719460,
  "lang"=>"fr"},
 {"text"=>
   "tribus font allégeance à un certain Mohammed. \nCe dernier a un grand
 projet : fonder un nouvel  ",
  "duration"=>5580,
  "offset"=>723900,
  "lang"=>"fr"},
 {"text"=>
   "empire musulman. Portés par un puissant élan \nreligieux, les cavalie
rs arabes déferlent sur",
  "duration"=>4740,
  "offset"=>729480,
  "lang"=>"fr"},
 {"text"=>
   "le Nord. Depuis longtemps, ils subissent les \nambitions de leurs pui
ssants voisins ! Et maintenant,  ",
  "duration"=>4680,
  "offset"=>734220,
  "lang"=>"fr"},
 {"text"=>
   "c’est à leur tour de faire trembler la \nPerse et Byzance ! Alors, ra
ssurez-vous,  ",
  "duration"=>3900,
  "offset"=>738900,
  "lang"=>"fr"},
 {"text"=>
   "vous aurez très bientôt la suite, \non aura l’occasion de parler des
 ",
  "duration"=>3360,
  "offset"=>742800,
  "lang"=>"fr"},
 {"text"=>
   "conquêtes islamiques, va falloir ouvrir l'œil !\nMerci à Lucas Pacott
e d’avoir écrit cet  ",
  "duration"=>4080,
  "offset"=>746160,
  "lang"=>"fr"},
 {"text"=>
   "épisode, merci à vous de l’avoir regardé !\nSi ça vous a plu comme d'hab, un like,  ",
  "duration"=>3520,
  "offset"=>750240,
  "lang"=>"fr"},
 {"text"=>
   "un partage, un commentaire, et abonnez vous \npour pas louper les prochaines vidéos ! Salut !",
  "duration"=>5520,
  "offset"=>753760,
  "lang"=>"fr"}]
)


content = Content.create!(
id: 24,
 source_type: "youtube_video",
 url: "https://www.youtube.com/watch?v=5eJSss02gAQ",
 thumbnail: "https://i.ytimg.com/vi/5eJSss02gAQ/maxresdefault.jpg",
 name: "Chronologie de l'astronomie 🚀",
 duration: 394,
 language: "fr",
 summary:"L'astronomie, une discipline fascinante depuis des millénaires, trouve ses origines dans les pratiques religieuses préhistoriques. Nos ancêtres, notamment en Mésopotamie, commencèrent à observer la lune et le soleil, tandis que les Babyloniens nommèrent les planètes visibles à l'œil nu et constituèrent des constellations. En Égypte, on créa le calendrier de 365 jours, divisant l'année en 12 mois et le jour en 24 heures. La Grèce antique, avec Aristote et Aristarque, contribua grandement à l'astronomie, bien que les idées géocentriques dominèrent jusqu'à Copernic.\n\nAu Moyen Âge, les Arabes préservèrent le savoir grec, tandis que Copernic au XVIe siècle révolutionna l'astronomie avec son modèle héliocentrique. Tycho Brahe accumula des observations précises, et Kepler découvrit que les planètes se mouvaient en ellipses autour du soleil. Galilée utilisa la lunette astronomique pour confirmer le modèle copernicien, bien que contraint à se rétracter par l'Inquisition. Plus tard, Isaac Newton formula la loi de la gravitation universelle, expliquant les mouvements planétaires.\n\nLe XIXe siècle vit des avancées comme la spectroscopie et la photographie, permettant d'analyser la composition chimique des astres. Le XXe siècle fut marqué par la relativité générale d'Einstein, qui prédit des phénomènes comme les ondes gravitationnelles et les trous noirs. L'expansion de l'univers fut découverte par Edwin Hubble et théorisée par Georges Lemaître, posant les bases de la cosmologie moderne avec le modèle du Big Bang. Enfin, Stephen Hawking contribua à unifier les lois de la nature, explorant les mystères des trous noirs et de l'univers.",
 user_id: jean.id,
 transcription:
 [{"text"=>"depuis longtemps très longtemps",
    "duration"=>4670,
    "offset"=>1770,
    "lang"=>"fr"},
   {"text"=>"l'astronomie fascine les civilisations",
    "duration"=>7140,
    "offset"=>3810,
    "lang"=>"fr"},
   {"text"=>"[Musique]", "duration"=>6430, "offset"=>6440, "lang"=>"fr"},
   {"text"=>"elle est sûrement la plus ancienne des",
    "duration"=>3660,
    "offset"=>10950,
    "lang"=>"fr"},
   {"text"=>"sciences naturelles et on retrouve ses",
    "duration"=>2849,
    "offset"=>12870,
    "lang"=>"fr"},
   {"text"=>"origines dans les pratiques religieuses",
    "duration"=>2250,
    "offset"=>14610,
    "lang"=>"fr"},
   {"text"=>"préhistorique",
    "duration"=>2671,
    "offset"=>15719,
    "lang"=>"fr"},
   {"text"=>"alors ce que je te propose c'est de",
    "duration"=>3120,
    "offset"=>16860,
    "lang"=>"fr"},
   {"text"=>"remonter un peu dans le temps l'espace",
    "duration"=>3299,
    "offset"=>18390,
    "lang"=>"fr"},
   {"text"=>"de quelques instants pour revivre les",
    "duration"=>2939,
    "offset"=>19980,
    "lang"=>"fr"},
   {"text"=>"plus grandes découvertes de notre",
    "duration"=>3500,
    "offset"=>21689,
    "lang"=>"fr"},
   {"text"=>"histoire", "duration"=>2270, "offset"=>22919, "lang"=>"fr"},
   {"text"=>"space", "duration"=>9240, "offset"=>26869, "lang"=>"fr"},
   {"text"=>"[Musique]",
    "duration"=>8099,
    "offset"=>28010,
    "lang"=>"fr"},
   {"text"=>"environ 4000 ans avant notre ère",
    "duration"=>3430,
    "offset"=>38790,
    "lang"=>"fr"},
   {"text"=>"l'astronomie prend ses racines en",
    "duration"=>2220,
    "offset"=>40750,
    "lang"=>"fr"},
   {"text"=>"mésopotamie",
    "duration"=>2610,
    "offset"=>42220,
    "lang"=>"fr"},
   {"text"=>"ce sont les babyloniens qui ont commencé",
    "duration"=>3300,
    "offset"=>42970,
    "lang"=>"fr"},
   {"text"=>"à noter les heures de lever et de",
    "duration"=>3620,
    "offset"=>44830,
    "lang"=>"fr"},
   {"text"=>"coucher de la lune et du soleil",
    "duration"=>4500,
    "offset"=>46270,
    "lang"=>"fr"},
   {"text"=>"ils ont regroupé les étoiles en",
    "duration"=>4210,
    "offset"=>48450,
    "lang"=>"fr"},
   {"text"=>"constellation et commence à comprendre",
    "duration"=>3570,
    "offset"=>50770,
    "lang"=>"fr"},
   {"text"=>"comment fonctionnait le ciel ayant",
    "duration"=>3450,
    "offset"=>52660,
    "lang"=>"fr"},
   {"text"=>"observé que les cinq planètes visible à",
    "duration"=>3030,
    "offset"=>54340,
    "lang"=>"fr"},
   {"text"=>"l'oeil nu se déplacer sur le fond",
    "duration"=>4909,
    "offset"=>56110,
    "lang"=>"fr"},
   {"text"=>"lointain des étoiles ils les ont nommés",
    "duration"=>3649,
    "offset"=>57370,
    "lang"=>"fr"},
   {"text"=>"chinois ont réussi ressembler à",
    "duration"=>4000,
    "offset"=>61290,
    "lang"=>"fr"},
   {"text"=>"conserver le plus grand nombre",
    "duration"=>3450,
    "offset"=>63640,
    "lang"=>"fr"},
   {"text"=>"d'observations pendant près de quatre",
    "duration"=>3270,
    "offset"=>65290.00000000001,
    "lang"=>"fr"},
   {"text"=>"mille ans et n'ont cessé de relever dans",
    "duration"=>3000,
    "offset"=>67090,
    "lang"=>"fr"},
   {"text"=>"leurs moindres détails les conjonctions",
    "duration"=>3360,
    "offset"=>68560,
    "lang"=>"fr"},
   {"text"=>"planétaire et les mouvements célestes",
    "duration"=>3960,
    "offset"=>70090,
    "lang"=>"fr"},
   {"text"=>"ils ont établi un calendrier précis des",
    "duration"=>3780,
    "offset"=>71920,
    "lang"=>"fr"},
   {"text"=>"carte stellaire répertoriait pour la",
    "duration"=>3390,
    "offset"=>74050,
    "lang"=>"fr"},
   {"text"=>"première fois des ellipses de soleil les",
    "duration"=>3360,
    "offset"=>75700,
    "lang"=>"fr"},
   {"text"=>"étoiles nouvelles et les apparitions de",
    "duration"=>3100,
    "offset"=>77440,
    "lang"=>"fr"},
   {"text"=>"comètes", "duration"=>4900, "offset"=>79060, "lang"=>"fr"},
   {"text"=>"au troisième millénaire votre autant des",
    "duration"=>5430,
    "offset"=>80540,
    "lang"=>"fr"},
   {"text"=>"pyramides les égyptiens ont créé notre",
    "duration"=>4980,
    "offset"=>83960,
    "lang"=>"fr"},
   {"text"=>"calendrier de 365 jours la division de",
    "duration"=>4920,
    "offset"=>85970,
    "lang"=>"fr"},
   {"text"=>"l'année en 12 mois et celle du jour en",
    "duration"=>3530,
    "offset"=>88940,
    "lang"=>"fr"},
   {"text"=>"24 heures",
    "duration"=>3810,
    "offset"=>90890,
    "lang"=>"fr"},
   {"text"=>"l'histoire de l'astronomie se poursuit",
    "duration"=>3490,
    "offset"=>92470,
    "lang"=>"fr"},
   {"text"=>"dans la grèce antique",
    "duration"=>2760,
    "offset"=>94700,
    "lang"=>"fr"},
   {"text"=>"aristote et la plupart des philosophes",
    "duration"=>3210,
    "offset"=>95960,
    "lang"=>"fr"},
   {"text"=>"de l'époque pensaient que le ciel tout",
    "duration"=>3540,
    "offset"=>97460,
    "lang"=>"fr"},
   {"text"=>"entier tourné autour de la terre",
    "duration"=>4200,
    "offset"=>99170,
    "lang"=>"fr"},
   {"text"=>"laquelle était supposé être fixé est",
    "duration"=>4320,
    "offset"=>101000,
    "lang"=>"fr"},
   {"text"=>"parfaitement immobile au centre de",
    "duration"=>2490,
    "offset"=>103370,
    "lang"=>"fr"},
   {"text"=>"l'univers",
    "duration"=>2460,
    "offset"=>105320,
    "lang"=>"fr"},
   {"text"=>"on arrive 300 ans avant notre ère",
    "duration"=>3990,
    "offset"=>105860,
    "lang"=>"fr"},
   {"text"=>"aristarque affirmant au contraire que la",
    "duration"=>3390,
    "offset"=>107780,
    "lang"=>"fr"},
   {"text"=>"terre tournait non seulement sur elle",
    "duration"=>3780,
    "offset"=>109850,
    "lang"=>"fr"},
   {"text"=>"même mais aussi autour du soleil des",
    "duration"=>4410,
    "offset"=>111170,
    "lang"=>"fr"},
   {"text"=>"idées irrecevable pour l'époque un autre",
    "duration"=>3780,
    "offset"=>113630,
    "lang"=>"fr"},
   {"text"=>"glock sport a dressé le premier",
    "duration"=>3870,
    "offset"=>115580,
    "lang"=>"fr"},
   {"text"=>"catalogue des toiles du monde occidental",
    "duration"=>3810,
    "offset"=>117410,
    "lang"=>"fr"},
   {"text"=>"il a découvert la pression des équinoxes",
    "duration"=>3750,
    "offset"=>119450,
    "lang"=>"fr"},
   {"text"=>"et inventer l'astrolabe tandis qu'à",
    "duration"=>3840,
    "offset"=>121220,
    "lang"=>"fr"},
   {"text"=>"alexandrie et rast hautaine à calculer",
    "duration"=>3360,
    "offset"=>123200,
    "lang"=>"fr"},
   {"text"=>"correctement la circonférence de la",
    "duration"=>4140,
    "offset"=>125060,
    "lang"=>"fr"},
   {"text"=>"terre environ 40000 km au deuxième",
    "duration"=>4860,
    "offset"=>126560,
    "lang"=>"fr"},
   {"text"=>"siècle claude tous les meilleurs donc",
    "duration"=>4470,
    "offset"=>129199.99999999999,
    "lang"=>"fr"},
   {"text"=>"d'expliquer mouvement complexe et pleine",
    "duration"=>3840,
    "offset"=>131420,
    "lang"=>"fr"},
   {"text"=>"d'ambition voire la théorie mathématique",
    "duration"=>4350,
    "offset"=>133670,
    "lang"=>"fr"},
   {"text"=>"des épicycle selon lui en tournant",
    "duration"=>5040,
    "offset"=>135260,
    "lang"=>"fr"},
   {"text"=>"autour de la terre les planètes effectué",
    "duration"=>4019.9999999999995,
    "offset"=>138020,
    "lang"=>"fr"},
   {"text"=>"en plus de petits cercles sur leur",
    "duration"=>4290,
    "offset"=>140300,
    "lang"=>"fr"},
   {"text"=>"orbite la réputation de tollé mais était",
    "duration"=>4169,
    "offset"=>142040,
    "lang"=>"fr"},
   {"text"=>"telle que cette erreur persistent a",
    "duration"=>3720,
    "offset"=>144590,
    "lang"=>"fr"},
   {"text"=>"longtemps même après le déclin de la",
    "duration"=>4310,
    "offset"=>146209,
    "lang"=>"fr"},
   {"text"=>"grée", "duration"=>2209, "offset"=>148310, "lang"=>"fr"},
   {"text"=>"au cours des siècles qui suivent le",
    "duration"=>3429,
    "offset"=>151840,
    "lang"=>"fr"},
   {"text"=>"flambeau de la science grecque fut",
    "duration"=>3390,
    "offset"=>154280,
    "lang"=>"fr"},
   {"text"=>"repris par les astronomes arabe tandis",
    "duration"=>3961,
    "offset"=>155269,
    "lang"=>"fr"},
   {"text"=>"qu'en occident la chrétienneté avait",
    "duration"=>5819,
    "offset"=>157670,
    "lang"=>"fr"},
   {"text"=>"rejeté tout le savoir antique fallu",
    "duration"=>6420,
    "offset"=>159230,
    "lang"=>"fr"},
   {"text"=>"attendre le polonais nicolas copernic au",
    "duration"=>3541,
    "offset"=>163489,
    "lang"=>"fr"},
   {"text"=>"xvième siècle pour que ressurgisse",
    "duration"=>3360,
    "offset"=>165650,
    "lang"=>"fr"},
   {"text"=>"l'hypothèse héliocentrique selon",
    "duration"=>3569,
    "offset"=>167030,
    "lang"=>"fr"},
   {"text"=>"laquelle la terre tourne autour du",
    "duration"=>3539,
    "offset"=>169010,
    "lang"=>"fr"},
   {"text"=>"soleil en un an en même temps que sur",
    "duration"=>4230,
    "offset"=>170599,
    "lang"=>"fr"},
   {"text"=>"elle-même en 24 heures mais il était",
    "duration"=>3541,
    "offset"=>172549,
    "lang"=>"fr"},
   {"text"=>"encore trop tôt pour que cela puisse",
    "duration"=>3601,
    "offset"=>174829,
    "lang"=>"fr"},
   {"text"=>"être accepté quelques décennies après la",
    "duration"=>4110,
    "offset"=>176090,
    "lang"=>"fr"},
   {"text"=>"mort de nicolas copernic l'astronome",
    "duration"=>3690,
    "offset"=>178430,
    "lang"=>"fr"},
   {"text"=>"danois tycho brahé accumulaient des",
    "duration"=>3390,
    "offset"=>180200,
    "lang"=>"fr"},
   {"text"=>"observations précises sur le mouvement",
    "duration"=>2850,
    "offset"=>182120,
    "lang"=>"fr"},
   {"text"=>"des planètes classe et un millier des",
    "duration"=>3090,
    "offset"=>183590,
    "lang"=>"fr"},
   {"text"=>"toiles et sur une île du danemark",
    "duration"=>2639,
    "offset"=>184970,
    "lang"=>"fr"},
   {"text"=>"il construit le premier grand",
    "duration"=>2290,
    "offset"=>186680,
    "lang"=>"fr"},
   {"text"=>"observatoire",
    "duration"=>2691,
    "offset"=>187609,
    "lang"=>"fr"},
   {"text"=>"[Musique]",
    "duration"=>4570,
    "offset"=>188970,
    "lang"=>"fr"},
   {"text"=>"au début du xviie siècle les précisions",
    "duration"=>4980,
    "offset"=>190300,
    "lang"=>"fr"},
   {"text"=>"de bras et ont permis au génial kepler",
    "duration"=>3210,
    "offset"=>193540,
    "lang"=>"fr"},
   {"text"=>"de comprendre que les planètes tournait",
    "duration"=>3360,
    "offset"=>195280,
    "lang"=>"fr"},
   {"text"=>"autour du soleil en suivant des ellipses",
    "duration"=>4380,
    "offset"=>196750,
    "lang"=>"fr"},
   {"text"=>"il a découvert les trois lois régissant",
    "duration"=>6150,
    "offset"=>198640,
    "lang"=>"fr"},
   {"text"=>"leur mouvement est posée le beuc loti en",
    "duration"=>6420,
    "offset"=>201130,
    "lang"=>"fr"},
   {"text"=>"1609 galilée a utilisé pour la première",
    "duration"=>4740,
    "offset"=>204790,
    "lang"=>"fr"},
   {"text"=>"fois une lunette astronomique pour",
    "duration"=>4170,
    "offset"=>207550,
    "lang"=>"fr"},
   {"text"=>"observer le ciel il a découvert les",
    "duration"=>4070.0000000000005,
    "offset"=>209530,
    "lang"=>"fr"},
   {"text"=>"lunes de jupiter",
    "duration"=>4910,
    "offset"=>211720,
    "lang"=>"fr"},
   {"text"=>"les phases de vénus",
    "duration"=>5670,
    "offset"=>213600,
    "lang"=>"fr"},
   {"text"=>"et les reliefs de la lune autant de",
    "duration"=>4260,
    "offset"=>216630,
    "lang"=>"fr"},
   {"text"=>"choses qui n'étaient pas explicable par",
    "duration"=>3600,
    "offset"=>219270,
    "lang"=>"fr"},
   {"text"=>"l'astronomie de ptolémée galilée se",
    "duration"=>3000,
    "offset"=>220890,
    "lang"=>"fr"},
   {"text"=>"prononcer en faveur du système",
    "duration"=>3510,
    "offset"=>222870,
    "lang"=>"fr"},
   {"text"=>"copernicien mais en 1633 il dû se",
    "duration"=>3720,
    "offset"=>223890,
    "lang"=>"fr"},
   {"text"=>"rétracter devant le tribunal de",
    "duration"=>1860,
    "offset"=>226380,
    "lang"=>"fr"},
   {"text"=>"l'inquisition",
    "duration"=>2670,
    "offset"=>227610,
    "lang"=>"fr"},
   {"text"=>"il fallut encore attendre 50 ans pour",
    "duration"=>3570,
    "offset"=>228240,
    "lang"=>"fr"},
   {"text"=>"qu'un autre génie de l'histoire point",
    "duration"=>3450,
    "offset"=>230280,
    "lang"=>"fr"},
   {"text"=>"que le bouton b l'anglais isaac newton",
    "duration"=>4470,
    "offset"=>231810,
    "lang"=>"fr"},
   {"text"=>"découvre 1687 la loi de l'attraction",
    "duration"=>5310,
    "offset"=>233730,
    "lang"=>"fr"},
   {"text"=>"universelle une force de gravité qui",
    "duration"=>5580,
    "offset"=>236280,
    "lang"=>"fr"},
   {"text"=>"attire autres tous les torts motif il",
    "duration"=>4380,
    "offset"=>239040,
    "lang"=>"fr"},
   {"text"=>"expliquait ainsi les lois de kepler sur",
    "duration"=>3330,
    "offset"=>241860,
    "lang"=>"fr"},
   {"text"=>"les mouvements planétaires et participer",
    "duration"=>3390,
    "offset"=>243420,
    "lang"=>"fr"},
   {"text"=>"à la naissance de l'astronomie moderne",
    "duration"=>4050,
    "offset"=>245190,
    "lang"=>"fr"},
   {"text"=>"isaac newton a également compris que la",
    "duration"=>4290,
    "offset"=>246810,
    "lang"=>"fr"},
   {"text"=>"lumière du soleil passant à travers un",
    "duration"=>4140,
    "offset"=>249240,
    "lang"=>"fr"},
   {"text"=>"prisme se décomposait en couleurs celles",
    "duration"=>4230,
    "offset"=>251100,
    "lang"=>"fr"},
   {"text"=>"de l'arc en ciel et il a construit le",
    "duration"=>3630,
    "offset"=>253380,
    "lang"=>"fr"},
   {"text"=>"premier télescope à réflexion en",
    "duration"=>3210,
    "offset"=>255330,
    "lang"=>"fr"},
   {"text"=>"utilisant non plus des lentilles comme",
    "duration"=>3449,
    "offset"=>257010,
    "lang"=>"fr"},
   {"text"=>"galilée mais un miroir pour collecter et",
    "duration"=>4830,
    "offset"=>258540.00000000003,
    "lang"=>"fr"},
   {"text"=>"focaliser la lumière douze découvertes",
    "duration"=>5191,
    "offset"=>260459,
    "lang"=>"fr"},
   {"text"=>"fondamentales ont marqué la fin du 19e",
    "duration"=>2790,
    "offset"=>263370,
    "lang"=>"fr"},
   {"text"=>"siècle", "duration"=>2190, "offset"=>265650, "lang"=>"fr"},
   {"text"=>"la spectroscopie ou l'analyse de la",
    "duration"=>3300,
    "offset"=>266160,
    "lang"=>"fr"},
   {"text"=>"lumière des astres permet d'en révéler",
    "duration"=>3420,
    "offset"=>267840,
    "lang"=>"fr"},
   {"text"=>"leur composition chimique et la",
    "duration"=>3480,
    "offset"=>269460,
    "lang"=>"fr"},
   {"text"=>"photographie qui permet de répertorier",
    "duration"=>3600,
    "offset"=>271260,
    "lang"=>"fr"},
   {"text"=>"systématiquement un grand nombre",
    "duration"=>3900,
    "offset"=>272940,
    "lang"=>"fr"},
   {"text"=>"d'objets célestes au déficit xxème",
    "duration"=>3480,
    "offset"=>274860,
    "lang"=>"fr"},
   {"text"=>"siècle une nouvelle théorie de la",
    "duration"=>3120,
    "offset"=>276840,
    "lang"=>"fr"},
   {"text"=>"gravitation encore plus complète que",
    "duration"=>3150,
    "offset"=>278340,
    "lang"=>"fr"},
   {"text"=>"celle d'isaac newton a vu le jour",
    "duration"=>5060,
    "offset"=>279960,
    "lang"=>"fr"},
   {"text"=>"la relativité générale d'albert einstein",
    "duration"=>5910,
    "offset"=>281490,
    "lang"=>"fr"},
   {"text"=>"non seulement alors mieux compte des",
    "duration"=>4090,
    "offset"=>285020,
    "lang"=>"fr"},
   {"text"=>"détails les plus fins du système solaire",
    "duration"=>3450,
    "offset"=>287400,
    "lang"=>"fr"},
   {"text"=>"mais elle prédit également de nouveaux",
    "duration"=>3450,
    "offset"=>289110,
    "lang"=>"fr"},
   {"text"=>"phénomènes qui seront tous découverts",
    "duration"=>3240,
    "offset"=>290850,
    "lang"=>"fr"},
   {"text"=>"ultérieurement comme les ondes",
    "duration"=>3380,
    "offset"=>292560,
    "lang"=>"fr"},
   {"text"=>"gravitationnelles",
    "duration"=>5810,
    "offset"=>294090,
    "lang"=>"fr"},
   {"text"=>"les trous noirs et le big bang",
    "duration"=>6370,
    "offset"=>295940,
    "lang"=>"fr"},
   {"text"=>"en parallèle les premiers télescopes",
    "duration"=>3700,
    "offset"=>299900,
    "lang"=>"fr"},
   {"text"=>"géants sont entrés en fonctionnement en",
    "duration"=>3300,
    "offset"=>302310,
    "lang"=>"fr"},
   {"text"=>"californie grâce à eux les astronomes",
    "duration"=>3750,
    "offset"=>303600,
    "lang"=>"fr"},
   {"text"=>"américains parmi lesquels edwin hubble",
    "duration"=>4260,
    "offset"=>305610,
    "lang"=>"fr"},
   {"text"=>"ont prouvé la nature extragalactique des",
    "duration"=>4620,
    "offset"=>307350,
    "lang"=>"fr"},
   {"text"=>"nébuleuses spirale et découvert leur",
    "duration"=>4260,
    "offset"=>309870,
    "lang"=>"fr"},
   {"text"=>"décalage spectral vers le rouge sont",
    "duration"=>3390,
    "offset"=>311970,
    "lang"=>"fr"},
   {"text"=>"toutefois pouvoir leur donner de",
    "duration"=>3630,
    "offset"=>314130,
    "lang"=>"fr"},
   {"text"=>"justification physique c'est le belge",
    "duration"=>5190,
    "offset"=>315360,
    "lang"=>"fr"},
   {"text"=>"georges lemaître qui en 1927 a compris",
    "duration"=>4409,
    "offset"=>317760,
    "lang"=>"fr"},
   {"text"=>"que le phénomène était due à l'expansion",
    "duration"=>5250,
    "offset"=>320550,
    "lang"=>"fr"},
   {"text"=>"de l'univers ont 1931 il a posé les",
    "duration"=>6301,
    "offset"=>322169,
    "lang"=>"fr"},
   {"text"=>"bases de la cosmologie moderne et de ces",
    "duration"=>6000,
    "offset"=>325800,
    "lang"=>"fr"},
   {"text"=>"fameux modèle du big bang aujourd'hui la",
    "duration"=>4800,
    "offset"=>328470,
    "lang"=>"fr"},
   {"text"=>"recherche est devenue essentiellement",
    "duration"=>3420,
    "offset"=>331800,
    "lang"=>"fr"},
   {"text"=>"collective de sorte à ce que l'histoire",
    "duration"=>4200,
    "offset"=>333270,
    "lang"=>"fr"},
   {"text"=>"future ne retiendra probablement pas de",
    "duration"=>4319,
    "offset"=>335220,
    "lang"=>"fr"},
   {"text"=>"nom savant au même titre qu'un copernic",
    "duration"=>5850,
    "offset"=>337470,
    "lang"=>"fr"},
   {"text"=>"kepler un newton einstein",
    "duration"=>6860,
    "offset"=>339539,
    "lang"=>"fr"},
   {"text"=>"[Musique]",
    "duration"=>3079,
    "offset"=>343320,
    "lang"=>"fr"},
   {"text"=>"stephen hawking a réussi à réunir tous",
    "duration"=>3870,
    "offset"=>349500,
    "lang"=>"fr"},
   {"text"=>"les domaines connus de loi de la nature",
    "duration"=>4140,
    "offset"=>352020,
    "lang"=>"fr"},
   {"text"=>"dans cette formule la seule formule de",
    "duration"=>5040,
    "offset"=>353370,
    "lang"=>"fr"},
   {"text"=>"gravitation quantique connu à ce jour on",
    "duration"=>4200,
    "offset"=>356160,
    "lang"=>"fr"},
   {"text"=>"pourra peut-être wendelin théorie qui",
    "duration"=>3390,
    "offset"=>358410,
    "lang"=>"fr"},
   {"text"=>"nous donnerait des informations sur la",
    "duration"=>3510,
    "offset"=>360360,
    "lang"=>"fr"},
   {"text"=>"naissance de notre univers et sur ce qui",
    "duration"=>3870,
    "offset"=>361800,
    "lang"=>"fr"},
   {"text"=>"se passe dans la singularité des trous",
    "duration"=>3260,
    "offset"=>363870,
    "lang"=>"fr"},
   {"text"=>"noirs", "duration"=>3810, "offset"=>365670, "lang"=>"fr"},
   {"text"=>"c'était le premier épisode de ma série",
    "duration"=>2950,
    "offset"=>367130,
    "lang"=>"fr"},
   {"text"=>"sur l'univers",
    "duration"=>1890,
    "offset"=>369480,
    "lang"=>"fr"},
   {"text"=>"si tu as aimé tu peux mettre un pouce",
    "duration"=>4050,
    "offset"=>370080,
    "lang"=>"fr"},
   {"text"=>"bleus est abonné à ma chaîne à bientôt",
    "duration"=>5760,
    "offset"=>371370,
    "lang"=>"fr"},
   {"text"=>"delory", "duration"=>3000, "offset"=>374130, "lang"=>"fr"},
   {"text"=>"[Musique]",
    "duration"=>3169,
    "offset"=>388860,
    "lang"=>"fr"}]
)

content = Content.create!(
id: 26,
 source_type: "youtube_video",
 url: "https://www.youtube.com/watch?v=sNhhvQGsMEc",
 thumbnail:
  "https://i.ytimg.com/vi/sNhhvQGsMEc/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBMP5UCoJhac-Wj9g-lDST0aBrFHQ",
 name: "The Fermi Paradox — Where Are All The Aliens? (1/2)",
 duration: 380,
 language: "en",
 summary:"Le texte explore la possibilité d'existence de vie extraterrestre dans l'univers. Il décrit l'immensité de l'univers observable, qui contient au moins 100 milliards de galaxies, chacune avec des milliards d'étoiles et potentiellement des trillions de planètes habitables. Cette abondance devrait, en théorie, offrir de nombreuses opportunités pour le développement de la vie.\n\nCependant, malgré cette possibilité, nous n'avons pas encore détecté d'autres civilisations, un phénomène souvent décrit comme le paradoxe de Fermi. Une hypothèse suggère que les civilisations avancées pourraient être trop éloignées pour être détectées en raison de l'expansion de l'univers, rendant toute communication impossible avec celles en dehors de notre groupe local de galaxies.\n\nLa discussion se concentre ensuite sur les différentes catégories de civilisations avancées, selon la théorie de Kardashev, qui mesure le niveau de développement technologique d'une civilisation basé sur l'énergie qu'elle peut utiliser. Une civilisation de type 1 utilise toute l'énergie disponible sur sa planète, de type 2 utilise l'énergie de son étoile, et de type 3 contrôle l'énergie de sa galaxie entière.\n\nLe texte aborde aussi le concept de \"grands filtres\", des barrières hypothétiques qui empêcheraient le développement ou la survie de civilisations avancées. Ces filtres pourraient être derrière nous, ce qui signifierait que la vie complexe est rarissime, ou devant nous, impliquant des obstacles que nous n'avons pas encore rencontrés.\n\nEnfin, le texte évoque la possibilité que nous soyons seuls dans l'univers. Cela soulève des questions existentielles sur notre place dans l'univers et sur l'importance de préserver la vie sur Terre. Il conclut en soulignant la beauté de l'univers et la nécessité de continuer à explorer et à préserver la vie pour en faire l'expérience.",
 user_id: jean.id,
 transcription: [
  {"text"=>"are we the only living things in the",
    "offset"=>80,
    "duration"=>3839,
    "lang"=>"en"},
   {"text"=>"entire universe",
    "offset"=>2399,
    "duration"=>4000,
    "lang"=>"en"},
   {"text"=>"the observable universe is about 90",
    "offset"=>3919,
    "duration"=>4961,
    "lang"=>"en"},
   {"text"=>"billion light years in diameter there",
    "offset"=>6399,
    "duration"=>5441,
    "lang"=>"en"},
   {"text"=>"are at least 100 billion galaxies each",
    "offset"=>8880,
    "duration"=>7040,
    "lang"=>"en"},
   {"text"=>"with 100 to 1 000 billion stars recently",
    "offset"=>11840,
    "duration"=>6000,
    "lang"=>"en"},
   {"text"=>"we've learned that planets are very",
    "offset"=>15920,
    "duration"=>3119,
    "lang"=>"en"},
   {"text"=>"common too",
    "offset"=>17840,
    "duration"=>3199,
    "lang"=>"en"},
   {"text"=>"and there are probably trillions and",
    "offset"=>19039,
    "duration"=>4000,
    "lang"=>"en"},
   {"text"=>"trillions of habitable planets in the",
    "offset"=>21039,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"universe which means there should be",
    "offset"=>23039,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"lots of opportunity for life to develop",
    "offset"=>25359,
    "duration"=>4961,
    "lang"=>"en"},
   {"text"=>"and exist right but where is it",
    "offset"=>27439,
    "duration"=>4721,
    "lang"=>"en"},
   {"text"=>"shouldn't the universe be teeming with",
    "offset"=>30320,
    "duration"=>4980,
    "lang"=>"en"},
   {"text"=>"spaceships let's take a step back",
    "offset"=>32160,
    "duration"=>8340,
    "lang"=>"en"},
   {"text"=>"[Music]",
    "offset"=>35300,
    "duration"=>5200,
    "lang"=>"en"},
   {"text"=>"even if there are alien civilizations in",
    "offset"=>41360,
    "duration"=>4960,
    "lang"=>"en"},
   {"text"=>"other galaxies there's no way we'll ever",
    "offset"=>44079,
    "duration"=>4480,
    "lang"=>"en"},
   {"text"=>"know about them basically everything",
    "offset"=>46320,
    "duration"=>4160,
    "lang"=>"en"},
   {"text"=>"outside of our direct galactic",
    "offset"=>48559,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"neighborhood the so-called local group",
    "offset"=>50480,
    "duration"=>4800,
    "lang"=>"en"},
   {"text"=>"is pretty much out of our reach forever",
    "offset"=>52879,
    "duration"=>4961,
    "lang"=>"en"},
   {"text"=>"because of the expansion of the universe",
    "offset"=>55280,
    "duration"=>5200,
    "lang"=>"en"},
   {"text"=>"even if we had really fast spaceships it",
    "offset"=>57840,
    "duration"=>4640,
    "lang"=>"en"},
   {"text"=>"would literally take billions of years",
    "offset"=>60480,
    "duration"=>4079,
    "lang"=>"en"},
   {"text"=>"to reach these places",
    "offset"=>62480,
    "duration"=>4319,
    "lang"=>"en"},
   {"text"=>"traveling through the emptiest areas in",
    "offset"=>64559,
    "duration"=>3441,
    "lang"=>"en"},
   {"text"=>"the universe",
    "offset"=>66799,
    "duration"=>3841,
    "lang"=>"en"},
   {"text"=>"so let's focus on the milky way the",
    "offset"=>68000,
    "duration"=>5439,
    "lang"=>"en"},
   {"text"=>"milky way is our home galaxy it consists",
    "offset"=>70640,
    "duration"=>5920,
    "lang"=>"en"},
   {"text"=>"of up to 400 billion stars that's a lot",
    "offset"=>73439,
    "duration"=>5521,
    "lang"=>"en"},
   {"text"=>"of stars counting one per second it",
    "offset"=>76560,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"would take you a hundred lifetimes to",
    "offset"=>78960,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"count them all there are about 20",
    "offset"=>80960,
    "duration"=>4799,
    "lang"=>"en"},
   {"text"=>"billion sun-like stars in the milky way",
    "offset"=>83360,
    "duration"=>4399,
    "lang"=>"en"},
   {"text"=>"and estimates suggest that a fifth of",
    "offset"=>85759,
    "duration"=>3841,
    "lang"=>"en"},
   {"text"=>"them have an earth-sized planet in its",
    "offset"=>87759,
    "duration"=>3921,
    "lang"=>"en"},
   {"text"=>"habitable zone the area with conditions",
    "offset"=>89600,
    "duration"=>6080,
    "lang"=>"en"},
   {"text"=>"that enable life to exist if only 0.1 of",
    "offset"=>91680,
    "duration"=>5920,
    "lang"=>"en"},
   {"text"=>"those planets harbored life there would",
    "offset"=>95680,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"be one million planets with life in the",
    "offset"=>97600,
    "duration"=>5360,
    "lang"=>"en"},
   {"text"=>"milky way but wait there's more the",
    "offset"=>100000,
    "duration"=>6000,
    "lang"=>"en"},
   {"text"=>"milky way is about 13 billion years old",
    "offset"=>102960,
    "duration"=>4560,
    "lang"=>"en"},
   {"text"=>"in the beginning it would not have been",
    "offset"=>106000,
    "duration"=>3439,
    "lang"=>"en"},
   {"text"=>"a good place for life because things",
    "offset"=>107520,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"exploded a lot but after one to two",
    "offset"=>109439,
    "duration"=>4401,
    "lang"=>"en"},
   {"text"=>"billion years the first habitable",
    "offset"=>111840,
    "duration"=>4239,
    "lang"=>"en"},
   {"text"=>"planets were born earth is only 4",
    "offset"=>113840,
    "duration"=>4319,
    "lang"=>"en"},
   {"text"=>"billion years old so there have probably",
    "offset"=>116079,
    "duration"=>4080,
    "lang"=>"en"},
   {"text"=>"been trillions of chances for life to",
    "offset"=>118159,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"develop on other planets in the past if",
    "offset"=>120159,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"only a single one of them had developed",
    "offset"=>122479,
    "duration"=>3361,
    "lang"=>"en"},
   {"text"=>"into a space traveling super",
    "offset"=>124479,
    "duration"=>3280,
    "lang"=>"en"},
   {"text"=>"civilization we would have noticed by",
    "offset"=>125840,
    "duration"=>2800,
    "lang"=>"en"},
   {"text"=>"now",
    "offset"=>127759,
    "duration"=>3681,
    "lang"=>"en"},
   {"text"=>"what would such a civilization look like",
    "offset"=>128640,
    "duration"=>4880,
    "lang"=>"en"},
   {"text"=>"there are three categories",
    "offset"=>131440,
    "duration"=>4799,
    "lang"=>"en"},
   {"text"=>"a type 1 civilization would be able to",
    "offset"=>133520,
    "duration"=>5040,
    "lang"=>"en"},
   {"text"=>"access the whole energy available on its",
    "offset"=>136239,
    "duration"=>4321,
    "lang"=>"en"},
   {"text"=>"planet in case you're wondering we're",
    "offset"=>138560,
    "duration"=>5280,
    "lang"=>"en"},
   {"text"=>"currently around 0.73 on the scale and",
    "offset"=>140560,
    "duration"=>5440,
    "lang"=>"en"},
   {"text"=>"we should reach type 1 sometime in the",
    "offset"=>143840,
    "duration"=>4080,
    "lang"=>"en"},
   {"text"=>"next couple of hundred years",
    "offset"=>146000,
    "duration"=>4560,
    "lang"=>"en"},
   {"text"=>"type 2 would be a civilization capable",
    "offset"=>147920,
    "duration"=>4560,
    "lang"=>"en"},
   {"text"=>"of harnessing all of the energy of its",
    "offset"=>150560,
    "duration"=>4160,
    "lang"=>"en"},
   {"text"=>"home style this would require some",
    "offset"=>152480,
    "duration"=>4640,
    "lang"=>"en"},
   {"text"=>"serious science fiction but it is doable",
    "offset"=>154720,
    "duration"=>4640,
    "lang"=>"en"},
   {"text"=>"in principle concepts like the dyson",
    "offset"=>157120,
    "duration"=>4640,
    "lang"=>"en"},
   {"text"=>"sphere a giant complex surrounding the",
    "offset"=>159360,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"sun would be conceivable",
    "offset"=>161760,
    "duration"=>4479,
    "lang"=>"en"},
   {"text"=>"type 3 is a civilization that basically",
    "offset"=>163760,
    "duration"=>5360,
    "lang"=>"en"},
   {"text"=>"controls its whole galaxy and its energy",
    "offset"=>166239,
    "duration"=>4961,
    "lang"=>"en"},
   {"text"=>"an alien race this advance would",
    "offset"=>169120,
    "duration"=>4160,
    "lang"=>"en"},
   {"text"=>"probably be god-like to us",
    "offset"=>171200,
    "duration"=>4319,
    "lang"=>"en"},
   {"text"=>"but why should we be able to see such an",
    "offset"=>173280,
    "duration"=>4720,
    "lang"=>"en"},
   {"text"=>"alien civilization in the first place",
    "offset"=>175519,
    "duration"=>4241,
    "lang"=>"en"},
   {"text"=>"if we were to build generation",
    "offset"=>178000,
    "duration"=>3280,
    "lang"=>"en"},
   {"text"=>"spaceships that could sustain a",
    "offset"=>179760,
    "duration"=>4160,
    "lang"=>"en"},
   {"text"=>"population for around 1 000 years we",
    "offset"=>181280,
    "duration"=>4800,
    "lang"=>"en"},
   {"text"=>"could colonize the whole galaxy in 2",
    "offset"=>183920,
    "duration"=>4800,
    "lang"=>"en"},
   {"text"=>"million years sounds like a long time",
    "offset"=>186080,
    "duration"=>5519,
    "lang"=>"en"},
   {"text"=>"but remember the milky way is huge",
    "offset"=>188720,
    "duration"=>4879,
    "lang"=>"en"},
   {"text"=>"so if it takes a couple of million years",
    "offset"=>191599,
    "duration"=>4321,
    "lang"=>"en"},
   {"text"=>"to colonize the entire galaxy and there",
    "offset"=>193599,
    "duration"=>5201,
    "lang"=>"en"},
   {"text"=>"are possibly millions if not billions of",
    "offset"=>195920,
    "duration"=>4640,
    "lang"=>"en"},
   {"text"=>"planets that sustain life in the milky",
    "offset"=>198800,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"way and these other life forms have had",
    "offset"=>200560,
    "duration"=>4800,
    "lang"=>"en"},
   {"text"=>"considerably more time than we've had",
    "offset"=>203120,
    "duration"=>3280,
    "lang"=>"en"},
   {"text"=>"then",
    "offset"=>205360,
    "duration"=>3040,
    "lang"=>"en"},
   {"text"=>"where are all the aliens",
    "offset"=>206400,
    "duration"=>5119,
    "lang"=>"en"},
   {"text"=>"this is the fermi paradox and nobody has",
    "offset"=>208400,
    "duration"=>4399,
    "lang"=>"en"},
   {"text"=>"an answer to it",
    "offset"=>211519,
    "duration"=>3841,
    "lang"=>"en"},
   {"text"=>"but we do have some ideas let's talk",
    "offset"=>212799,
    "duration"=>5520,
    "lang"=>"en"},
   {"text"=>"about filters a filter in this context",
    "offset"=>215360,
    "duration"=>5200,
    "lang"=>"en"},
   {"text"=>"represents a barrier that is really hard",
    "offset"=>218319,
    "duration"=>4000,
    "lang"=>"en"},
   {"text"=>"for life to overcome",
    "offset"=>220560,
    "duration"=>4720,
    "lang"=>"en"},
   {"text"=>"they come in various degrees of scary",
    "offset"=>222319,
    "duration"=>6401,
    "lang"=>"en"},
   {"text"=>"one there are great filters and we have",
    "offset"=>225280,
    "duration"=>4560,
    "lang"=>"en"},
   {"text"=>"passed them",
    "offset"=>228720,
    "duration"=>3680,
    "lang"=>"en"},
   {"text"=>"maybe it is way harder for complex life",
    "offset"=>229840,
    "duration"=>4959,
    "lang"=>"en"},
   {"text"=>"to develop than we think the process",
    "offset"=>232400,
    "duration"=>4559,
    "lang"=>"en"},
   {"text"=>"allowing life to begin hasn't yet been",
    "offset"=>234799,
    "duration"=>3601,
    "lang"=>"en"},
   {"text"=>"completely figured out and the",
    "offset"=>236959,
    "duration"=>3521,
    "lang"=>"en"},
   {"text"=>"conditions required may be really",
    "offset"=>238400,
    "duration"=>3280,
    "lang"=>"en"},
   {"text"=>"complicated",
    "offset"=>240480,
    "duration"=>3600,
    "lang"=>"en"},
   {"text"=>"maybe in the past the universe was way",
    "offset"=>241680,
    "duration"=>4720,
    "lang"=>"en"},
   {"text"=>"more hostile and only recently have",
    "offset"=>244080,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"things cooled down to make complex life",
    "offset"=>246400,
    "duration"=>4080,
    "lang"=>"en"},
   {"text"=>"possible this would also mean that we",
    "offset"=>248480,
    "duration"=>4080,
    "lang"=>"en"},
   {"text"=>"may be unique or at least one of the",
    "offset"=>250480,
    "duration"=>5039,
    "lang"=>"en"},
   {"text"=>"first if not the first civilization in",
    "offset"=>252560,
    "duration"=>4959,
    "lang"=>"en"},
   {"text"=>"the entire universe",
    "offset"=>255519,
    "duration"=>4801,
    "lang"=>"en"},
   {"text"=>"two there are great filters and they are",
    "offset"=>257519,
    "duration"=>3921,
    "lang"=>"en"},
   {"text"=>"ahead of us",
    "offset"=>260320,
    "duration"=>3439,
    "lang"=>"en"},
   {"text"=>"this one would be really really bad",
    "offset"=>261440,
    "duration"=>4080,
    "lang"=>"en"},
   {"text"=>"maybe life on our level exists",
    "offset"=>263759,
    "duration"=>3521,
    "lang"=>"en"},
   {"text"=>"everywhere in the universe but it gets",
    "offset"=>265520,
    "duration"=>3440,
    "lang"=>"en"},
   {"text"=>"destroyed when it reaches a certain",
    "offset"=>267280,
    "duration"=>4720,
    "lang"=>"en"},
   {"text"=>"point a point that lies ahead of us",
    "offset"=>268960,
    "duration"=>5440,
    "lang"=>"en"},
   {"text"=>"for example awesome future technology",
    "offset"=>272000,
    "duration"=>4960,
    "lang"=>"en"},
   {"text"=>"exists but when activated it destroys",
    "offset"=>274400,
    "duration"=>4799,
    "lang"=>"en"},
   {"text"=>"the planet the last words of every",
    "offset"=>276960,
    "duration"=>4560,
    "lang"=>"en"},
   {"text"=>"advanced civilization would be this new",
    "offset"=>279199,
    "duration"=>4161,
    "lang"=>"en"},
   {"text"=>"device will solve all of our problems",
    "offset"=>281520,
    "duration"=>4399,
    "lang"=>"en"},
   {"text"=>"once i push this button if this is true",
    "offset"=>283360,
    "duration"=>4880,
    "lang"=>"en"},
   {"text"=>"then we are closer to the end than the",
    "offset"=>285919,
    "duration"=>5041,
    "lang"=>"en"},
   {"text"=>"beginning of human existence or maybe",
    "offset"=>288240,
    "duration"=>5200,
    "lang"=>"en"},
   {"text"=>"there is an ancient type 3 civilization",
    "offset"=>290960,
    "duration"=>4799,
    "lang"=>"en"},
   {"text"=>"that monitors the universe and once a",
    "offset"=>293440,
    "duration"=>5120,
    "lang"=>"en"},
   {"text"=>"civilization is advanced enough it gets",
    "offset"=>295759,
    "duration"=>5041,
    "lang"=>"en"},
   {"text"=>"eliminated in an instant",
    "offset"=>298560,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"maybe there is something out there that",
    "offset"=>300800,
    "duration"=>4800,
    "lang"=>"en"},
   {"text"=>"it would be better not to discover",
    "offset"=>302960,
    "duration"=>4799,
    "lang"=>"en"},
   {"text"=>"there is no way for us to know",
    "offset"=>305600,
    "duration"=>5039,
    "lang"=>"en"},
   {"text"=>"one final thought maybe we're alone",
    "offset"=>307759,
    "duration"=>5041,
    "lang"=>"en"},
   {"text"=>"right now we have no evidence that",
    "offset"=>310639,
    "duration"=>4241,
    "lang"=>"en"},
   {"text"=>"there's any life besides us",
    "offset"=>312800,
    "duration"=>4880,
    "lang"=>"en"},
   {"text"=>"nothing the universe appears to be empty",
    "offset"=>314880,
    "duration"=>5599,
    "lang"=>"en"},
   {"text"=>"and dead no one's sending us messages no",
    "offset"=>317680,
    "duration"=>4959,
    "lang"=>"en"},
   {"text"=>"one answering our calls we may be",
    "offset"=>320479,
    "duration"=>5121,
    "lang"=>"en"},
   {"text"=>"completely alone trapped on a tiny moist",
    "offset"=>322639,
    "duration"=>5681,
    "lang"=>"en"},
   {"text"=>"mud wall in an eternal universe does",
    "offset"=>325600,
    "duration"=>4800,
    "lang"=>"en"},
   {"text"=>"that thought scare you if it does you're",
    "offset"=>328320,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"having the correct emotional reaction",
    "offset"=>330400,
    "duration"=>4320,
    "lang"=>"en"},
   {"text"=>"if we let life on this planet die",
    "offset"=>332720,
    "duration"=>4160,
    "lang"=>"en"},
   {"text"=>"perhaps there will be no life left in",
    "offset"=>334720,
    "duration"=>4400,
    "lang"=>"en"},
   {"text"=>"the universe life will be gone maybe",
    "offset"=>336880,
    "duration"=>5039,
    "lang"=>"en"},
   {"text"=>"forever if this is the case we just have",
    "offset"=>339120,
    "duration"=>4480,
    "lang"=>"en"},
   {"text"=>"to venture to the stars and become the",
    "offset"=>341919,
    "duration"=>3840,
    "lang"=>"en"},
   {"text"=>"first type 3 civilization to keep the",
    "offset"=>343600,
    "duration"=>4240,
    "lang"=>"en"},
   {"text"=>"delicate flame of life existing and to",
    "offset"=>345759,
    "duration"=>3681,
    "lang"=>"en"},
   {"text"=>"spread it until the universe breathes",
    "offset"=>347840,
    "duration"=>3680,
    "lang"=>"en"},
   {"text"=>"its final breath and vanishes into",
    "offset"=>349440,
    "duration"=>3120,
    "lang"=>"en"},
   {"text"=>"oblivion",
    "offset"=>351520,
    "duration"=>3360,
    "lang"=>"en"},
   {"text"=>"the universe is too beautiful not to be",
    "offset"=>352560,
    "duration"=>4000,
    "lang"=>"en"},
   {"text"=>"experienced by someone",
    "offset"=>354880,
    "duration"=>3599,
    "lang"=>"en"},
   {"text"=>"[Music]",
    "offset"=>356560,
    "duration"=>3919,
    "lang"=>"en"},
   {"text"=>"this video was made possible by your",
    "offset"=>358479,
    "duration"=>3280,
    "lang"=>"en"},
   {"text"=>"support",
    "offset"=>360479,
    "duration"=>3521,
    "lang"=>"en"},
   {"text"=>"it takes at least 200 hours to make one",
    "offset"=>361759,
    "duration"=>3921,
    "lang"=>"en"},
   {"text"=>"of our videos and thanks to your",
    "offset"=>364000,
    "duration"=>4000,
    "lang"=>"en"},
   {"text"=>"contributions on patreon we are slowly",
    "offset"=>365680,
    "duration"=>4480,
    "lang"=>"en"},
   {"text"=>"able to do more and more of them if you",
    "offset"=>368000,
    "duration"=>4319,
    "lang"=>"en"},
   {"text"=>"want to help us out and get your own",
    "offset"=>370160,
    "duration"=>4319,
    "lang"=>"en"},
   {"text"=>"personal bird for example check out the",
    "offset"=>372319,
    "duration"=>5720,
    "lang"=>"en"},
   {"text"=>"patreon page",
    "offset"=>374479,
    "duration"=>3560,
    "lang"=>"en"},
   {"text"=>"you",
    "offset"=>380000,
    "duration"=>2080,
    "lang"=>"en"}]
)
puts "✅ #{Content.count} Contents créés : #{Content.pluck(:name).join(', ')}"
